config/routes.rb
Rails.application.routes.draw do

  resources :follows, constraints: {onlyajax: true}, only: [:create, :destroy]
  devise_for :users
  resources :posts, except: [:new]
  resources :comments, constraints: {onlyajax: true}, except: [:show, :new, :edit, :index]
  resources :profiles
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  validates :user, uniqueness: true
  validates :dob, date: {before: Proc.new {Time.now - 16.year}}
  validates :first_name, :surname, length: {minimum: 2, maximum: 20}
  validates :first_name, :surname, format: {with: /\A([A-Z][a-z\-]+)+\z/, message: "must start with capital"}
  validates :bio, length: {maximum: 300}

  has_many :posts, dependent: :destroy
  validates_associated :posts
  has_many :comments, dependent: :destroy
  validates_associated :comments
  belongs_to :user


  has_many :followersR, foreign_key: :follower_id , class_name: "Follow"
  has_many :followed, through: :followersR, class_name: "Profile"
  has_many :followedR, foreign_key: :followed_id, class_name: "Follow"
  has_many :followers, through: :followedR, class_name: "Profile"

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include ApplicationHelper
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_profile, except: [:new, :create]
  before_action :authenticate_user!, only: [:new, :create]
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all()
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    if current_user.profile
      redirect_to edit_profile_path(current_user.profile)
    else
      @profile = Profile.new
      @profile.user = current_user
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:first_name, :surname, :dob, :bio, :picture_url)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
.container
  = form_for @profile do |f|
    - if @profile.errors.any?
      #error_explanation
        %h2= "#{pluralize(@profile.errors.count, "error")} #{t('create_failed',class: "profile")}"
        %ul
          - @profile.errors.full_messages.each do |message|
            %li= message
    .row.justify-content-center
      .col-auto
        = f.label :Name
      .col-auto
        .field
          = f.text_field :first_name
      .col-auto
        .field
          = f.text_field :surname
    .row.justify-content-center
      .col-auto
        .field
          = f.label :dob
          = f.date_select :dob, :start_year=>1940
    .row.justify-content-center
      .col-auto
        .field
          = f.label :bio
          = f.text_area :bio
    .row.justify-content-center
      .col-auto
        .actions
          = f.submit t('.save'), class: "btn btn-secondary"

app/views/profiles/_listShow.html.haml
.row.justify-content-start.bg-primary.profileListShow{"id" => "profile#{profile.id}"}
  .col-auto
    -if profile.picture_url
      = image_tag(profile.picture_url)
    -else
      = image_tag('defaultProfile.png')

  %a.col-auto{'href' => profile_path(profile)}
    %p.name
      ="#{profile.first_name}  #{profile.surname}"
  .col-auto
    -if current_user.profile == profile
      .btn-group
        = button_to t('.edit'), edit_profile_path(profile) , method: :get, class: "btn btn-light"
        = button_to t('.delete'), profile, method: :delete, remote: true, data: { confirm: t('confirm') }, class: "btn btn-light"
    -else
      -if current_user.profile.followed.include?(profile)
        -follow = Follow.find_by(follower_id: current_user.profile.id, followed_id: profile.id)
        = button_to t('.unfollow'), follow , method: :delete, remote: true, class: "btn btn-light"
      -else
        = button_to t('.follow'), follows_path(:method => :post, follow:{follower_id: current_user.profile.id, followed_id: profile.id}),  remote: true, class: "btn btn-light"
  .col-auto
    %p.text-white
      =t('.followers')
      = profile.followers.size()

app/views/profiles/edit.html.haml
= render 'form'

app/views/profiles/index.html.haml
.container
  - @profiles.each do |profile|
    - unless current_user.profile == profile
      = render 'listShow', profile: profile

app/views/profiles/new.html.haml
= render 'form'

app/views/profiles/show.html.haml
.container
  =render 'listShow', profile: @profile
  .row
    .col
      %h.elementTitle
        =t('.bio')
      %p.textBlock
        =@profile.bio
.container
  .row
    .col
      %h1
        = t('postsNav')
  .row
    -@profile.posts.each do |post|
      =render 'posts/show', post: post, comment_depth: 5