config/routes.rb
Rails.application.routes.draw do

  resources :follows, constraints: {onlyajax: true}, only: [:create, :destroy]
  devise_for :users
  resources :posts, except: [:new]
  resources :comments, constraints: {onlyajax: true}, except: [:show, :new, :edit, :index]
  resources :profiles
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_profile
  #before_action User.authenticate_profile()
  def home
  end

  def contact
  end

  def request_contact
    name = params[:name]
    email = params[:email]
    telephone = params[:telephone]
    message = params[:message]

    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    else
      ContactMailer.contact_email(email, name, telephone, message).deliver_now
      flash[:notice] =  I18n.t('home.request_contact.email_sent')
    end
    redirect_to root_path
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/contact.html.haml
%h1= t('.title')
%p= t('.contact_us')

= form_tag request_contact_path, method: 'post' do

  = label_tag :name, t('.name')
  = text_field_tag :name, '', title: t('.enter_name'), size: 50

  = label_tag :email, t('.email')
  = email_field_tag :email, '', title: t('.enter_email')

  = label_tag :telephone, t('.telephone')
  = text_field_tag :message, '', title: t('.enter_telephone')

  = label_tag :message, t('.message')
  = text_field_tag :message, '', title: t('.enter_message'), size: 100

  = submit_tag t('.submit')

app/views/home/home.html.haml
%p= t('.title')