config/routes.rb
Rails.application.routes.draw do

  resources :follows, constraints: {onlyajax: true}, only: [:create, :destroy]
  devise_for :users
  resources :posts, except: [:new]
  resources :comments, constraints: {onlyajax: true}, except: [:show, :new, :edit, :index]
  resources :profiles
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'
  root 'home#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, uniqueness: true
  validates :title, presence: true
  belongs_to :profile
  has_many :comments, dependent: :destroy
  scope :followed, ->(user) {
    followedProfiles = user.profile.followed
    where(:profile => followedProfiles)}
  scope :feed, ->(user) {
    Post.followed(user) + user.profile.posts
   }
   scope :search, ->(query) {
     Post.where("title like ?","%#{query}%") + Post.where("post_text like ?","%#{query}%")
   }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ApplicationHelper
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_profile
  # GET /posts
  # GET /posts.json
  def index
    @post = Post.new
    if params[:query]
      @posts = Post.search(params[:query])
    else
      @posts = Post.feed(current_user)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.profile = current_user.profile
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
      else
        #form is at top of index view so the index view must be rendered if failed to create
        @posts = Post.feed(current_user)
        format.html { render :index}
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.'}
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :post_text)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
.container
  .row
    = form_for post do |f|
      - if post.errors.any?
        #error_explanation
          %h2= "#{pluralize(post.errors.count, "error")} #{t('create_failed',class: "post")}"
          %ul
            - @post.errors.full_messages.each do |message|
              %li= message
      .field
        = f.label :title
        = f.text_field :title
      .field
        = f.text_area :post_text, class: "textarea"
      .actions
        = f.submit t('.create_post')

app/views/posts/_postComments.html.haml
.row
  .col
    %h.elementTitle Comments
-if comment_depth > 0
  -x = 0
  -post.comments.each do |comment|
    = render 'comments/show', comment: comment
    -x += 1
    -break if x == comment_depth
-else
  -post.comments.each do |comment|
    = render 'comments/show', comment: comment
.row#addCommentRow
  .col.form
    = render 'comments/form', comment: Comment.new,  post: post

app/views/posts/_show.html.haml
.container{'id' => "postContainer#{post.id}"}
  =render 'profiles/listShow', profile: post.profile
  .row
    %h.elementTitle
      = post.title
  .row
    .col.postText
      %p.textBlock
        = post.post_text
  = render 'posts/postComments', post: post, comment_depth: comment_depth

app/views/posts/_showPost.html.haml
%p#notice= notice
%div.container{'id' => "postContainer#{post.id}"}
  %div.row
    %div.col-auto
      -if post.profile.picture_url
        = image_tag(post.profile.picture_url)
      -else
        = image_tag('defaultProfile.png')
    %div.col-auto
      = post.profile.first_name
      = post.profile.surname
    %div.col-auto
      %div.btn-group{'role' => 'group'}
        -if current_user.profile == post.profile
          = button_to 'Edit', edit_post_path(post), class: "btn btn-secondary"
          -if comment_depth > 0
            = button_to 'Delete', post, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary"
          -else
            = button_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-secondary"
  %div.row
    %h
      = post.title
  %div.row
    %p
      = post.post_text
    -if post.image_url
      %image{'source' => post.image_url}
  -if comment_depth > 0
    -x = 0
    -post.comments.each do |comment|
      = render 'comments/show', comment: comment
      -x += 1
      -break if x == comment_depth
  -else
    -post.comments.each do |comment|
      = render 'comments/show', comment: comment
  %div.row#addCommentRow
    %div.col.form
      = render 'comments/form', comment: Comment.new,  post: post

app/views/posts/destroy.js.erb
$("#postContainer<%= @post.id %>").hide()

app/views/posts/edit.html.haml
= render 'form', post: @post
%div.container
  = render 'postComments', post: @post, comment_depth: 0

app/views/posts/index.html.haml
=render 'form', post: @post
- @posts.each do |post|
  =render 'show', post: post, comment_depth: 3

app/views/posts/show.html.haml
= render 'show', post: @post, comment_depth: 0